export enum AuditAction {
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS',
  UPDATE_QUOTE_STATUS = 'UPDATE_QUOTE_STATUS',
  DEACTIVATE_USER = 'DEACTIVATE_USER',
}

export enum AuditEntityType {
  PRODUCT = 'Product',
  ORDER = 'Order',
  QUOTE = 'Quote',
  USER = 'User',
}
